//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKS_Perpustakaan_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buku
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public buku()
        {
            this.peminjaman_buku = new HashSet<peminjaman_buku>();
        }
    
        public string kode_buku { get; set; }
        public string kode_lokasi { get; set; }
        public int id_kat { get; set; }
        public string judul { get; set; }
        public string penulis { get; set; }
        public string penerbit { get; set; }
        public string deskripsi { get; set; }
        public int harga { get; set; }
        public int stok { get; set; }
    
        public virtual kategori kategori { get; set; }
        public virtual lokasi lokasi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<peminjaman_buku> peminjaman_buku { get; set; }
    }
}
