//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKS_Perpustakaan_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lokasi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lokasi()
        {
            this.bukus = new HashSet<buku>();
        }
    
        public string kode_lokasi { get; set; }
        public string label { get; set; }
        public int lantai { get; set; }
        public string rak { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<buku> bukus { get; set; }
    }
}
