//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKS_Perpustakaan_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class peminjaman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public peminjaman()
        {
            this.peminjaman_buku = new HashSet<peminjaman_buku>();
        }
    
        public int id_pinjam { get; set; }
        public string id_anggota { get; set; }
        public string id_petugas { get; set; }
    
        public virtual anggota anggota { get; set; }
        public virtual petuga petuga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<peminjaman_buku> peminjaman_buku { get; set; }
    }
}
