//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKS_Perpustakaan_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class peminjaman_buku
    {
        public int id { get; set; }
        public string kode_buku { get; set; }
        public int id_pinjam { get; set; }
        public System.DateTime tgl_pinjam { get; set; }
        public System.DateTime tgl_kembali { get; set; }
        public Nullable<System.DateTime> tgl_kembali_riil { get; set; }
        public Nullable<int> denda { get; set; }
        public Nullable<int> jml_hari_denda { get; set; }
    
        public virtual buku buku { get; set; }
        public virtual peminjaman peminjaman { get; set; }
    }
}
